package net.iyun.goldyheart.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.fabricmc.fabric.api.tag.convention.v2.ConventionalItemTags;
import net.iyun.goldyheart.block.ModBlocks;
import net.iyun.goldyheart.item.ModItems;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.ItemTags;

import java.util.concurrent.CompletableFuture;

public class ModItemTagProvider extends FabricTagProvider.ItemTagProvider {

    public ModItemTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
        super(output, completableFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup arg) {


        getOrCreateTagBuilder(ItemTags.PLANKS)
                .add(ModBlocks.WEATHERED_PLANKS.asItem())
                .add(ModBlocks.DARK_SPIRAL_PLANKS.asItem())
                .add(ModBlocks.ANCIENT_PLANKS.asItem())
                .add(ModBlocks.SPIRAL_PLANKS.asItem())
                .add(ModBlocks.OLD_PLANKS.asItem());

        getOrCreateTagBuilder(ItemTags.MEAT)
                .add(ModItems.FRIEDCHICKEN)
                .add(ModItems.RAWCHICKENLEG)
                .add(ModItems.RAWBACON)
                .add(ModItems.COOKEDBACON)
                .add(ModItems.STEAKANDPOTATO);

        getOrCreateTagBuilder(ItemTags.LOGS_THAT_BURN)
                .add(ModBlocks.WEATHERED_LOG.asItem())
                .add(ModBlocks.ANCIENT_LOG.asItem())
                .add(ModBlocks.ANCIENT_WOOD.asItem())
                .add(ModBlocks.STRIPPED_ANCIENT_WOOD.asItem())
                .add(ModBlocks.STRIPPED_ANCIENT_LOG.asItem())
                .add(ModBlocks.SPIRAL_LOG.asItem())
                .add(ModBlocks.SPIRAL_WOOD.asItem())
                .add(ModBlocks.STRIPPED_SPIRAL_WOOD.asItem())
                .add(ModBlocks.STRIPPED_SPIRAL_LOG.asItem())
                .add(ModBlocks.DARK_SPIRAL_LOG.asItem())
                .add(ModBlocks.DARK_SPIRAL_WOOD.asItem())
                .add(ModBlocks.STRIPPED_DARK_SPIRAL_WOOD.asItem())
                .add(ModBlocks.STRIPPED_DARK_SPIRAL_LOG.asItem())
                .add(ModBlocks.OLD_LOG.asItem())
                .add(ModBlocks.OLD_WOOD.asItem())
                .add(ModBlocks.STRIPPED_OLD_LOG.asItem())
                .add(ModBlocks.STRIPPED_OLD_WOOD.asItem())
                .add(ModBlocks.STRIPPED_WEATHERED_LOG.asItem())
                .add(ModBlocks.STRIPPED_WEATHERED_WOOD.asItem())
                .add(ModBlocks.WEATHERED_WOOD.asItem());

        getOrCreateTagBuilder(ItemTags.STAIRS)
                .add(ModBlocks.WEATHERED_PLANK_STAIRS.asItem())
                .add(ModBlocks.AMETHYST_STAIRS.asItem())
                .add(ModBlocks.TUFF_STAIRS.asItem())
                .add(ModBlocks.COPPER_STAIRS.asItem())
                .add(ModBlocks.OXIDIZED_COPPER_STAIRS.asItem())
                .add(ModBlocks.WEATHERED_COPPER_STAIRS.asItem())
                .add(ModBlocks.EXPOSED_COPPER_STAIRS.asItem())
                .add(ModBlocks.SAND_STAIR.asItem())
                .add(ModBlocks.RED_SAND_STAIR.asItem())
                .add(ModBlocks.SMOOTH_BASALT_STAIRS.asItem())
                .add(ModBlocks.CALCITE_STAIRS.asItem())
                .add(ModBlocks.DEAD_BRAIN_CORAL_STAIRS.asItem())
                .add(ModBlocks.DEAD_FIRE_CORAL_STAIRS.asItem())
                .add(ModBlocks.DEAD_BUBBLE_CORAL_STAIRS.asItem())
                .add(ModBlocks.DEAD_HORN_CORAL_STAIRS.asItem())
                .add(ModBlocks.DEAD_TUBE_CORAL_STAIRS.asItem())
                .add(ModBlocks.OLD_STAIRS.asItem())
                .add(ModBlocks.FANCY_STAIRS.asItem())
                .add(ModBlocks.IRON_STAIRS.asItem())
                .add(ModBlocks.GOLD_STAIRS.asItem())
                .add(ModBlocks.SPIRAL_STAIRS.asItem())
                .add(ModBlocks.DARK_SPIRAL_STAIRS.asItem())
                .add(ModBlocks.ANCIENT_STAIRS.asItem());

        getOrCreateTagBuilder(ItemTags.LEAVES)
                .add(ModBlocks.ANCIENT_LEAVES.asItem())
                .add(ModBlocks.SPIRAL_LEAVES.asItem())
                .add(ModBlocks.DARK_SPIRAL_LEAVES.asItem())
                .add(ModBlocks.OLD_LEAVES.asItem());

        getOrCreateTagBuilder(ItemTags.SLABS)
                .add(ModBlocks.WEATHERED_PLANK_SLABS.asItem())
                .add(ModBlocks.OAK_WOOD_SLAB.asItem())
                .add(ModBlocks.OAK_WOOD_SLAB_S.asItem())
                .add(ModBlocks.BIRCH_WOOD_SLAB_S.asItem())
                .add(ModBlocks.BIRCH_WOOD_SLAB.asItem())
                .add(ModBlocks.OLD_SLAB.asItem())
                .add(ModBlocks.OLD_WOOD_SLAB_S.asItem())
                .add(ModBlocks.OLD_WOOD_SLAB.asItem())
                .add(ModBlocks.DARK_SPIRAL_SLAB.asItem())
                .add(ModBlocks.DARK_SPIRAL_WOOD_SLAB_S.asItem())
                .add(ModBlocks.DARK_SPIRAL_WOOD_SLAB.asItem())
                .add(ModBlocks.ANCIENT_SLAB.asItem())
                .add(ModBlocks.ACA_WOOD_SLAB.asItem())
                .add(ModBlocks.ACA_WOOD_SLAB_S.asItem())
                .add(ModBlocks.SPRUCE_WOOD_SLAB.asItem())
                .add(ModBlocks.SPRUCE_WOOD_SLAB_S.asItem())
                .add(ModBlocks.JUNGLE_WOOD_SLAB.asItem())
                .add(ModBlocks.JUNGLE_WOOD_SLAB_S.asItem())
                .add(ModBlocks.CHERRY_WOOD_SLAB.asItem())
                .add(ModBlocks.CHERRY_WOOD_SLAB_S.asItem())
                .add(ModBlocks.DARK_OAK_WOOD_SLAB.asItem())
                .add(ModBlocks.DARK_OAK_WOOD_SLAB_S.asItem())
                .add(ModBlocks.DIRT_SLAB.asItem())
                .add(ModBlocks.COARSE_DIRT_SLAB.asItem())
                .add(ModBlocks.ROOTED_DIRT_SLAB.asItem())
                .add(ModBlocks.SAND_SLAB.asItem())
                .add(ModBlocks.RED_SAND_SLAB.asItem())
                .add(ModBlocks.EXPOSED_COPPER_SLAB.asItem())
                .add(ModBlocks.WEATHERED_COPPER_SLAB.asItem())
                .add(ModBlocks.OXIDIZED_COPPER_SLAB.asItem())
                .add(ModBlocks.COPPER_SLAB.asItem())
                .add(ModBlocks.CALCITE_SLAB.asItem())
                .add(ModBlocks.WHITE_WOOL_SLAB.asItem())
                .add(ModBlocks.BLACK_WOOL_SLAB.asItem())
                .add(ModBlocks.GRAY_WOOL_SLAB.asItem())
                .add(ModBlocks.ORANGE_WOOL_SLAB.asItem())
                .add(ModBlocks.PURPLE_WOOL_SLAB.asItem())
                .add(ModBlocks.BROWN_WOOL_SLAB.asItem())
                .add(ModBlocks.MAGENTA_WOOL_SLAB.asItem())
                .add(ModBlocks.MOSS_SLAB.asItem())
                .add(ModBlocks.GRAVEL_SLAB.asItem())
                .add(ModBlocks.SMOOTH_BASALT_SLAB.asItem())
                .add(ModBlocks.PACKED_ICE_SLAB.asItem())
                .add(ModBlocks.OVERGROWN_GRASS.asItem())
                .add(ModBlocks.WEATHERED_PLANK_SLABS.asItem())
                .add(ModBlocks.SPIRAL_WOOD_SLAB_S.asItem())
                .add(ModBlocks.SPIRAL_WOOD_SLAB.asItem())
                .add(ModBlocks.DARK_SPIRAL_WOOD_SLAB_S.asItem())
                .add(ModBlocks.DARK_SPIRAL_WOOD_SLAB.asItem())
                .add(ModBlocks.ANCIENT_WOOD_SLAB.asItem())
                .add(ModBlocks.ANCIENT_WOOD_SLAB_S.asItem())
                .add(ModBlocks.FANCY_SLAB.asItem())
                .add(ModBlocks.CYAN_WOOL_SLAB.asItem())
                .add(ModBlocks.YELLOW_WOOL_SLAB.asItem())
                .add(ModBlocks.LIGHT_BLUE_WOOL_SLAB.asItem())
                .add(ModBlocks.LIGHT_GRAY_WOOL_SLAB.asItem())
                .add(ModBlocks.PINK_WOOL_SLAB.asItem())
                .add(ModBlocks.RED_WOOL_SLAB.asItem())
                .add(ModBlocks.BLUE_WOOL_SLAB.asItem())
                .add(ModBlocks.GREEN_WOOL_SLAB.asItem())
                .add(ModBlocks.LIME_WOOL_SLAB.asItem())
                .add(ModBlocks.IRON_SLAB.asItem())
                .add(ModBlocks.GOLD_SLAB.asItem())
                .add(ModBlocks.DEAD_BUBBLE_CORAL_SLAB.asItem())
                .add(ModBlocks.DEAD_FIRE_CORAL_SLAB.asItem())
                .add(ModBlocks.DEAD_HORN_CORAL_SLAB.asItem())
                .add(ModBlocks.DEAD_TUBE_CORAL_SLAB.asItem())
                .add(ModBlocks.DEAD_BRAIN_CORAL_SLAB.asItem())
                .add(ModBlocks.MANGROVE_WOOD_SLAB.asItem())
                .add(ModBlocks.MANGROVE_WOOD_SLAB_S.asItem());

        getOrCreateTagBuilder(ItemTags.TRAPDOORS);
              //  .add(ModBlocks.STONE_TRAPDOOR.asItem())
             //   .add(ModBlocks.COBBLESTONE_TRAPDOOR.asItem())
             //   .add(ModBlocks.GLASS_TRAPDOOR.asItem());

        getOrCreateTagBuilder(ItemTags.DOORS);
              //  .add(ModBlocks.OLD_DOOR.asItem())
        //    .add(ModBlocks.ANCIENT_DOOR.asItem())
        //    .add(ModBlocks.SPIRAL_DOOR.asItem())
        //      .add(ModBlocks.DARK_SPIRAL_DOOR.asItem());

        getOrCreateTagBuilder(ItemTags.BUTTONS);
                //    .add(ModBlocks.OLD_BUTTON.asItem())
                //     .add(ModBlocks.ANCIENT_BUTTON.asItem())
                //     .add(ModBlocks.SPIRAL_BUTTON.asItem())
        //   .add(ModBlocks.FANCY_BUTTON.asItem())
        //     .add(ModBlocks.DARK_SPIRAL_BUTTON.asItem());

        getOrCreateTagBuilder(ItemTags.WOOL)
                .add(ModBlocks.WHITE_WOOL_SLAB.asItem())
                .add(ModBlocks.BLUE_WOOL_SLAB.asItem())
                .add(ModBlocks.PURPLE_WOOL_SLAB.asItem())
                .add(ModBlocks.LIGHT_BLUE_WOOL_SLAB.asItem())
                .add(ModBlocks.LIGHT_GRAY_WOOL_SLAB.asItem())
                .add(ModBlocks.GRAY_WOOL_SLAB.asItem())
                .add(ModBlocks.GREEN_WOOL_SLAB.asItem())
                .add(ModBlocks.LIME_WOOL_SLAB.asItem())
                .add(ModBlocks.YELLOW_WOOL_SLAB.asItem())
                .add(ModBlocks.PINK_WOOL_SLAB.asItem())
                .add(ModBlocks.RED_WOOL_SLAB.asItem())
                .add(ModBlocks.MAGENTA_WOOL_SLAB.asItem())
                .add(ModBlocks.BROWN_WOOL_SLAB.asItem())
                .add(ModBlocks.ORANGE_WOOL_SLAB.asItem())
                .add(ModBlocks.CYAN_WOOL_SLAB.asItem())
                .add(ModBlocks.BLACK_WOOL_SLAB.asItem());

        getOrCreateTagBuilder(ConventionalItemTags.FOODS)
        .add(ModItems.ANCIENTFRUIT.asItem())
        .add(ModItems.SALT.asItem())
        .add(ModItems.BUCKETOFSALT.asItem())
        .add(ModItems.PEPPER.asItem())
        .add(ModItems.BUCKETOFPEPPER.asItem())
        .add(ModItems.BUTTER.asItem())
        .add(ModItems.MELTEDBUTTER.asItem())
        .add(ModItems.MARSHMELLOW.asItem())
        .add(ModItems.MARSHMELLOWSTICK.asItem())
        .add(ModItems.SLIGHTLYCOOKEDMARSHMELLOW.asItem())
        .add(ModItems.SLIGHTLYCOOKEDMARSHMELLOWSTICK.asItem())
        .add(ModItems.COOKEDMARSHMELLOW.asItem())
        .add(ModItems.COOKEDMARSHMELLOWSTICK.asItem())
        .add(ModItems.BURNTMARSHMELLOW.asItem())
        .add(ModItems.BURNTMARSHMELLOWSTICK.asItem())
        .add(ModItems.COPPERBERRY.asItem())
        .add(ModItems.COALBERRY.asItem())
        .add(ModItems.GOLDBERRY.asItem())
        .add(ModItems.EMERALDBERRY.asItem())
        .add(ModItems.IRONBERRY.asItem())
        .add(ModItems.LAPISBERRY.asItem())
        .add(ModItems.AMETHYSTBERRY.asItem())
        .add(ModItems.DIAMONDBERRY.asItem())
        .add(ModItems.NETHERITEBERRY.asItem())
        .add(ModItems.REDSTONEBERRY.asItem())
        .add(ModItems.NETHERQUARTZBERRY.asItem())
        .add(ModItems.BOILEDEGG.asItem())
        .add(ModItems.FRIEDEGG.asItem())
        .add(ModItems.EGGONBREAD.asItem())
        .add(ModItems.CUTBREAD.asItem())
        .add(ModItems.TRUFFLE.asItem())
        .add(ModItems.CANDIEDSPIDEREYE.asItem())
        .add(ModItems.RAWBACON.asItem())
        .add(ModItems.COOKEDBACON.asItem())
        .add(ModItems.TOMATO.asItem())
        .add(ModItems.CUTTOMATO.asItem())
        .add(ModItems.CUCUMBER.asItem())
        .add(ModItems.CUCUMBERSLICE.asItem())
        .add(ModItems.GRAPES.asItem())
        .add(ModItems.COFFEEBEAN.asItem())
        .add(ModItems.LETTUCE.asItem())
        .add(ModItems.LETTUCELEAF.asItem())
        .add(ModItems.APPLEPIE.asItem())
        .add(ModItems.CHOCOLATEPIE.asItem())
        .add(ModItems.CHEESEPIE.asItem())
        .add(ModItems.CHEESE.asItem())
        .add(ModItems.TOAST.asItem())
        .add(ModItems.TOAST2.asItem())
        .add(ModItems.CAKESLICE.asItem())
        .add(ModItems.CARROTCAKE.asItem())
        .add(ModItems.SWEETBERRYCAKE.asItem())
        .add(ModItems.GLOWBERRYCAKE.asItem())
        .add(ModItems.APPLECAKE.asItem())
        .add(ModItems.MELONSCAKE.asItem())
        .add(ModItems.CHORUSCAKE.asItem())
        .add(ModItems.BEETROOTCAKE.asItem())
        .add(ModItems.STRAWBERRYCAKE.asItem())
        .add(ModItems.BLUEBERRYCAKE.asItem())
        .add(ModItems.MUFFIN.asItem())
        .add(ModItems.APPLEMUFFIN.asItem())
        .add(ModItems.BLUEMUFFIN.asItem())
        .add(ModItems.STRAWMUFFIN.asItem())
        .add(ModItems.MELONMUFFIN.asItem())
        .add(ModItems.GLOWMUFFIN.asItem())
        .add(ModItems.CARROTMUFFIN.asItem())
        .add(ModItems.SWEETMUFFIN.asItem())
        .add(ModItems.CHOCOMUFFIN.asItem())
        .add(ModItems.PUMPKINMUFFIN.asItem())
        .add(ModItems.PICKELS.asItem())
        .add(ModItems.PICKELTOMATO.asItem())
        .add(ModItems.PICKELSTRAW.asItem())
        .add(ModItems.PICKELONION.asItem())
        .add(ModItems.PICKELCORN.asItem())
        .add(ModItems.PICKELCHILLI.asItem())
        .add(ModItems.PICKELCARROT.asItem())
        .add(ModItems.PICKELBLUE.asItem())
        .add(ModItems.PICKELBELL.asItem())
        .add(ModItems.PANCAKES.asItem())
        .add(ModItems.CROISSANT.asItem())
        .add(ModItems.WINE.asItem())
        .add(ModItems.GLOWWINE.asItem())
        .add(ModItems.BEETWINE.asItem())
        .add(ModItems.CHORUSWINE.asItem())
        .add(ModItems.MELONWINE.asItem())
        .add(ModItems.SWEETWINE.asItem())
        .add(ModItems.WHISKEY.asItem())
        .add(ModItems.BUTTEREDPOTATO.asItem())
        .add(ModItems.MASHEDPOTATOES.asItem())
        .add(ModItems.TOMATOSOUP.asItem())
        .add(ModItems.SPIDEREYESOUP.asItem())
        .add(ModItems.SALAD.asItem())
        .add(ModItems.PUMPKINSOUP.asItem())
        .add(ModItems.NOODLES.asItem())
        .add(ModItems.SPAGHETTI.asItem())
        .add(ModItems.STEAKANDPOTATO.asItem())
        .add(ModItems.DUMPLING.asItem())
        .add(ModItems.DOUGH.asItem())
        .add(ModItems.SPRINGROLL.asItem())
        .add(ModItems.STUFFEDMUSHROOM.asItem())
        .add(ModItems.NIGIRISUSHI.asItem())
        .add(ModItems.VEGGIEMAKI.asItem())
        .add(ModItems.VEGGIESANDWICH.asItem())
        .add(ModItems.HOTCHOCOLATE.asItem())
        .add(ModItems.COFFEE.asItem())
        .add(ModItems.CABBAGEMEATROLL.asItem())
        .add(ModItems.BURGER.asItem())
        .add(ModItems.APPLESMOOTHIE.asItem())
        .add(ModItems.CARROTSMOOTHIE.asItem())
        .add(ModItems.PUMPKINSMOOTHIE.asItem())
        .add(ModItems.SWEETBERRYSMOOTHIE.asItem())
        .add(ModItems.WATERMELONSMOOTHIE.asItem())
        .add(ModItems.GLOWBERRYSMOOTHIE.asItem())
        .add(ModItems.BLUEBERSMOOTHIE.asItem())
        .add(ModItems.STRAWBERSMOOTHIE.asItem())
        .add(ModItems.TOASTWITHBUTTER.asItem())
        .add(ModItems.TOASTWITHBACON.asItem())
        .add(ModItems.TOASTWITHJAM.asItem())
        .add(ModItems.TOASTWITHEGG.asItem())
        .add(ModItems.FRIEDCHICKEN.asItem())
        .add(ModItems.RAWCHICKENLEG.asItem())
        .add(ModItems.PARSLEY.asItem())
        .add(ModItems.ONION.asItem())
        .add(ModItems.ONIONSLICE.asItem())
        .add(ModItems.RAWONIONRING.asItem())
        .add(ModItems.FRIEDONIONRING.asItem())
        .add(ModItems.BELLPEPPER.asItem())
        .add(ModItems.BELLPEPPERSLICE.asItem())
        .add(ModItems.STUFFEDBELLPEPPER.asItem())
        .add(ModItems.GARLIC.asItem())
        .add(ModItems.GARLICBREAD.asItem())
        .add(ModItems.PIZZA.asItem())
        .add(ModItems.PIZZASLICE.asItem())
        .add(ModItems.DOUGHTNUT.asItem())
        .add(ModItems.BEETDONUT.asItem())
        .add(ModItems.CARROTDONUT.asItem())
        .add(ModItems.APPLEDONUT.asItem())
        .add(ModItems.BLUEDONUT.asItem())
        .add(ModItems.STRAWDONUT.asItem())
        .add(ModItems.SWEETDONUT.asItem())
        .add(ModItems.CHOCODONUT.asItem())
        .add(ModItems.MELONDONUT.asItem())
        .add(ModItems.CHORUSDONUT.asItem())
        .add(ModItems.GLOWDONUT.asItem())
        .add(ModItems.GLOWBERRYCAKESLICE.asItem())
        .add(ModItems.APPLECAKESLICE.asItem())
        .add(ModItems.SWEETBERRYCAKESLICE.asItem())
        .add(ModItems.WATERMELONCAKESLICE.asItem())
        .add(ModItems.CHORUSCAKESLICE.asItem())
        .add(ModItems.CARROTCAKESLICE.asItem())
        .add(ModItems.BEETROOTCAKESLICE.asItem())
        .add(ModItems.STRAWBERRYCAKESLICE.asItem())
        .add(ModItems.BLUEBERRYCAKESLICE.asItem())
        .add(ModItems.MELONJAM.asItem())
        .add(ModItems.CARROTJAM.asItem())
        .add(ModItems.CHORUSJAM.asItem())
        .add(ModItems.BEETJAM.asItem())
        .add(ModItems.SWEETJAM.asItem())
        .add(ModItems.GLOWJAM.asItem())
        .add(ModItems.BLUEBERJAM.asItem())
        .add(ModItems.STRAWJAM.asItem())
        .add(ModItems.APPLEJAM.asItem())
        .add(ModItems.GLOWCOOKIE.asItem())
        .add(ModItems.MELONCOOKIE.asItem())
        .add(ModItems.SWEETCOOKIE.asItem())
        .add(ModItems.BEETCOOKIE.asItem())
        .add(ModItems.CHORUSCOOKIE.asItem())
        .add(ModItems.BLUECOOKIE.asItem())
        .add(ModItems.STRAWCOOKIE.asItem())
        .add(ModItems.CHILLI.asItem())
        .add(ModItems.CORN.asItem())
        //     entries.add(ModItems.WORM);
        //   entries.add(ModItems.CANOFWORMS);
        //    entries.add(ModItems.WORMBOWL);
        .add(ModItems.STRAWBERRY.asItem())
        .add(ModItems.BLUEBERRY.asItem())
        .add(ModItems.PEARLSTEW.asItem())
        .add(ModItems.POPCORN.asItem())
        .add(ModItems.BUTTERCORN.asItem())
        .add(ModItems.SNIFFEROMLETTE.asItem())
        .add(ModItems.BOILEDSNIFFEGG.asItem())
        .add(ModItems.BLAZERODNOODLES.asItem())
        .add(ModItems.GRILLEDCORN.asItem())
        .add(ModItems.CHOCOSTRAWBERRY.asItem())
        .add(ModItems.RHUBARB.asItem())
        .add(ModItems.SANDBREAD.asItem());

        getOrCreateTagBuilder(ItemTags.VILLAGER_PLANTABLE_SEEDS)
        .add(ModItems.CHILLISEEDS.asItem())
        .add(ModItems.CORNSEEDS.asItem())
        .add(ModItems.CUCUMBERSEEDS.asItem())
        .add(ModItems.GRAPESEEDS.asItem())
        .add(ModItems.LETTUCESEEDS.asItem())
        .add(ModItems.PARSLEYSEEDS.asItem())
        .add(ModItems.RUHBARBSEEDS.asItem())
        .add(ModItems.TOMATOSEEDS.asItem())
        .add(ModItems.ANCIENTSEEDS.asItem())
        .add(ModItems.BELLPEPPERSEEDS.asItem());
    }
}

